defaults:
  - default
  - data: kitti_360
  - model_conf/backbone: default
  - _self_



name: "eval_voxel"
eval_type: "eval_voxel"
checkpoint: "checkpoints/ViPOcc-KITTI-360.pt"


log_every: 100
batch_size: 1
num_workers: 1

image_size: [192, 640]
points_on_ray: 64

data:
  image_size: ${image_size}
  data_segmentation: false
  return_fisheye: false
  return_stereo: false
  data_fc: 1
  is_preprocessed: true
  data_path: "data/KITTI-360"
  pose_path: "data/KITTI-360/data_poses"
  return_3d_bboxes: true
  bboxes_semantic_labels: ["car",]
  return_voxel: true

model_conf:
  arch: "BTSNet"
  use_code: true
  image_size: ${image_size}
  points_on_ray: ${points_on_ray}

  code:
    num_freqs: 6
    freq_factor: 1.5
    include_input: true

  backbone:
    use_depth_branch: true

  mlp_coarse:
    type: "resnet"
    n_blocks: 0
    d_hidden: 64

  mlp_fine:
    type: "resnet"
    n_blocks: 0
    d_hidden: 64

  z_near: 3
  z_far: 80

  ray_batch_size: 256
  code_mode: z
  inv_z: true
  learn_empty: false

  n_frames_encoder: 1
  n_frames_render: 1

  sample_color: true
  use_legacy_benchmark: false
  bbox_margin_ratio: 1.5

renderer:
  n_coarse: ${points_on_ray}
  n_fine: 0
  n_fine_depth: 0
  depth_std: 1.0
  sched: [ ]
  white_bkgd: false
  lindisp: true
  hard_alpha_cap: true
