defaults:
  - default
  - data: kitti_360
  - model_conf/backbone: default
  - _self_

name: "kitti_360"
model: "vipocc"
output_path: out/${name}/${model}

num_epochs: 25
#batch_size: 16
batch_size: 8
#visualize_every: 100
checkpoint_every: 500

points_on_ray: 64

save_best:
  metric: scene_O_acc
  sign: 1
  n_saved: 15

data:
  data_fc: 2
  image_size: [ 192, 640 ]
  color_aug: false # color aug is slow
  is_preprocessed: true
  fisheye_rotation: [ 0, -15 ]
  return_gt_depth: true
  return_pseudo_depth: true
  return_all_pseudo_depth: true
  return_3d_bboxes: false
  bboxes_semantic_labels: ["car",]
  return_voxel: true

model_conf:
  arch: "BTSNet"
  use_code: true
  image_size: ${data.image_size}
  points_on_ray: ${points_on_ray}
  prediction_mode: default

  code:
    num_freqs: 6
    freq_factor: 1.5
    include_input: true

  backbone:
    use_depth_branch: true
    rid_ablation: rid   # [rid, res_depth, depth]


  mlp_coarse:
    type: "resnet"
    n_blocks: 0
    d_hidden: 64

  mlp_fine:
    type: "resnet"
    n_blocks: 0
    d_hidden: 64

  z_near: 3
  z_far: 80
  x_range: [ -4.5, 4.5 ]
  y_range: ~ # [ -1.5, 2.5 ]
  z_range: [ 3, 20 ]
  # only eval gt depth in distance range [z_near, z_far]
  eval_w_dist_range: true
  eval_occ: true
  inv_z: true

  n_frames_encoder: 1
  n_frames_render: 2
  frame_sample_mode: kitti360-mono

  sample_mode: patch
  patch_size: 8
  ray_batch_size: 4096

  flip_augmentation: true

  learn_empty: false
  code_mode: z
  loss_disc_signal: "depth"

loss:
  criterion: "l1+ssim"
  invalid_policy: weight_guided
  lambda_depth_supervision: 0.0
  lambda_depth_recon: 0.005
  lambda_temporal_alignment: 0.01
  depth_recon_version: 1
  loss_sigma_weight: 0.00
  loss_disc_weight: 0.05
  loss_gap_weight: 0.00
  loss_gap_start_epoch: 10


scheduler:
  type: step
  step_size: 120000
  gamma: 0.1

renderer:
  n_coarse: ${points_on_ray}
  n_fine: 0
  n_fine_depth: 0
  depth_std: 1.0
  sched: [ ]
  white_bkgd: false
  lindisp: true
  hard_alpha_cap: true
  depth_align_teacher: false
  loss_disc_signal: ${model_conf.loss_disc_signal}
